import {buildEmails, classify, titles, VERSION} from './email-templates.js';
import {createSubmissionLedger, duplicateSubmissionMessage} from './submission-safety.mjs';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let lead=null, phase='idle', observer='', configured=false, afterHours=false, scenario='open';
let lines=[],bookings=[],callbacks=[],mailEvents=[],enquiries=[],voiceActive=false,voiceStopResolve=null;
let cursor={text:0,voice:0};let recognition=null;let channelBusy={text:false,voice:false};
const uid=()=>crypto.randomUUID();
const submissionLedger=createSubmissionLedger();
function text(tag,value,cls){const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function status(id,message){$(id).textContent=message;}
function allowed(){if(phase!=='active'){toast(phase==='finished'?'Demo finished. Start a new session to continue.':'Enter your details to start the demo.');return false;}return true;}
function activity(title,detail){const row=text('div',title,'activity-row');row.append(text('small',detail));$('#activity').prepend(row);}
function show(panel){$$('.tab').forEach(t=>{t.classList.toggle('active',t.dataset.panel===panel);t.setAttribute('aria-selected',String(t.dataset.panel===panel));});$$('.panel').forEach(p=>p.classList.toggle('active',p.id===panel));}
$$('.tab').forEach(b=>b.addEventListener('click',()=>show(b.dataset.panel)));
$('#openOwner').onclick=()=>show('owner');$('#openEmails').onclick=()=>show('emails');
$('#openFeedback').onclick=()=>show('feedback');
function message(value,who,channel){const row=text('div','','msg'+(who==='Customer'?' you':''));row.append(text('div',who.toUpperCase(),'who'),document.createTextNode(value));$('#messages').append(row);$('#messages').scrollTop=$('#messages').scrollHeight;lines.push({who,text:value,channel});}
function answer(q){const c=classify(q,afterHours),practice=lead?.business||'the practice',hours=`${$('#openTime')?.value||'09:00'}–${$('#closeTime')?.value||'17:00'}`;if(c.urgency.startsWith('Urgent'))return `Please contact ${practice} promptly. For trouble breathing, uncontrolled bleeding or severe swelling, seek emergency care. I can flag your enquiry for urgent staff review; this demo does not contact emergency services.`;if(/hour|open|clos|time/i.test(q))return afterHours?`This walkthrough is set to after hours. ${practice} will review enquiries at the next opening. The clinic configured its demo appointment window as ${hours}.`:`${practice} configured its demo appointment window as ${hours}. These are example hours, not verified practice availability.`;if(/book|appointment|visit/i.test(q))return 'Choose Book a visit. You can request direct booking or propose A, B and C independently; the clinic confirms the selected time.';if(/new patient|accept|register/i.test(q))return `I can record your new-patient enquiry for ${practice}. Choose a consultation in Book a visit, or request a callback.`;if(/price|cost|insurance/i.test(q))return 'The practice team will need to confirm fees and insurance. I can record a callback request.';return 'I can demonstrate opening hours, new-patient enquiries, bookings and callbacks. Treatment advice needs a dental professional.';}
function converse(q,channel){message(q,'Customer',channel);const response=answer(q);message(response,'Aileen',channel);enquiries.push({question:q,...classify(q,afterHours),channel});activity(`${channel} enquiry`,classify(q,afterHours).route);renderOwner();return response;}
function patientFields(prefix){return prefix==='callback'?{name:$('#callbackName').value.trim(),phone:$('#callbackPhone').value.trim(),email:$('#callbackEmail').value.trim()}:{name:$('#patientName').value.trim(),phone:$('#patientPhone').value.trim(),email:$('#patientEmail').value.trim()};}
$('#leadForm').addEventListener('submit',async e=>{
 e.preventDefault();if(phase==='finishing'||mailEvents.some(m=>m.busy)){toast('Wait for the current emails to finish before restarting.');return;}
 if(lead&&!window.confirm('Start a new demo session? This clears the current session history from this page.'))return;
 await stopVoice();window.speechSynthesis?.cancel();
 lead={name:$('#name').value.trim(),business:$('#business').value.trim(),email:$('#email').value.trim(),phone:$('#phone').value.trim(),website:$('#websiteUrl').value.trim(),timezone:$('#timezone').value,consent:$('#emailConsent').checked,scenario:$('#scenario').value,discovery:{interest:$('#interest').value.trim(),priority:$('#priority').value,currency:$('#currency').value,averageRevenue:$('#averageRevenue').value===''?null:Number($('#averageRevenue').value),missedAfterHours:$('#missedAfterHours').value===''?null:Number($('#missedAfterHours').value)}};
 afterHours=$('#scenario').value==='closed';scenario=$('#scenario').value;phase='active';lines=[];bookings=[];callbacks=[];enquiries=[];mailEvents=[];cursor={text:0,voice:0};channelBusy={text:false,voice:false};
 $('#messages').replaceChildren();$('#activity').replaceChildren();$('#emailEvents').replaceChildren();
 ['#textEmailStatus','#voiceEmailStatus','#bookingStatus','#callbackStatus'].forEach(s=>status(s,''));status('#transcript','Transcript will appear here.');
 $('#feedbackForm').reset();$('#feedbackStatus').textContent='';$('#finishDemo').disabled=false;
 $$('#leadForm input,#leadForm select').forEach(n=>{if(n.id!=='website')n.disabled=true;});$('#leadForm button').textContent='Edit discovery / start a new demo';
 $('#callbackName').value=lead.name;$('#callbackPhone').value=lead.phone;
 $('#patientName').value=lead.name;$('#patientPhone').value=lead.phone;
 message(`Welcome to ${lead.business}. ${afterHours?'The clinic is in its after-hours scenario. ':scenario==='urgent'?'This walkthrough is set to the urgent-patient scenario. ':''}How can I help?`,'Aileen','text');
 status('#gateStatus',`${lead.business} · ${scenario==='urgent'?'Urgent scenario':afterHours?'After hours':'Clinic hours'} · Discovery captured · Owner: ${lead.email}`);
 $('#roiResult').textContent='';$('#hoursBadge').textContent=`${$('#openTime').value}–${$('#closeTime').value}`;
 activity('Demo started','Session-only data');renderOwner();show('chat');if(scenario==='urgent')converse('I have severe facial swelling and difficulty breathing','text');
});
// A new session first unlocks the form so role details can be changed without changing an active session.
$('#leadForm button').addEventListener('click',e=>{if(lead&&$('#name').disabled){e.preventDefault();if(mailEvents.some(m=>m.busy)||phase==='finishing')return toast('Wait for email operations to finish.');if(!window.confirm('End this session and enter details for a new demo?'))return;phase='idle';stopVoice();$$('#leadForm input,#leadForm select').forEach(n=>n.disabled=false);$('#leadForm button').textContent='Start the demo';status('#gateStatus','Edit discovery, then start a new demo session.');}});
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();if(!allowed()||channelBusy.text)return;const q=$('#chatInput').value.trim();if(q){$('#chatInput').value='';converse(q.slice(0,2000),'text');}});
$$('.suggestions button').forEach(b=>b.onclick=()=>{if(allowed()&&!channelBusy.text)converse(b.textContent,'text');});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
if(SR){recognition=new SR();recognition.lang='en-IE';recognition.interimResults=true;recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const q=e.results[i][0].transcript;if(e.results[i].isFinal&&['active','finishing'].includes(phase)){const response=converse(q.slice(0,2000),'voice');if(phase==='active'&&!voiceStopResolve&&'speechSynthesis'in window)speechSynthesis.speak(new SpeechSynthesisUtterance(response));}else interim+=q;}status('#transcript',interim||lines.filter(l=>l.channel==='voice').slice(-4).map(l=>`${l.who}: ${l.text}`).join('\n'));};recognition.onend=()=>{voiceActive=false;$('#voiceStart').disabled=false;if(voiceStopResolve){voiceStopResolve();voiceStopResolve=null;}};recognition.onerror=e=>status('#transcript',`Voice input unavailable (${e.error}). You can continue with text.`);}
function stopVoice(){window.speechSynthesis?.cancel();if(!voiceActive||!recognition)return Promise.resolve();return new Promise(resolve=>{voiceStopResolve=resolve;recognition.stop();setTimeout(()=>{if(voiceStopResolve){recognition.abort();voiceActive=false;voiceStopResolve();voiceStopResolve=null;}},2500);});}
$('#voiceStart').onclick=()=>{if(!allowed()||channelBusy.voice)return;if(!recognition)return status('#transcript','Browser voice is unavailable. Use a supported browser or the text tab.');try{recognition.start();voiceActive=true;$('#voiceStart').disabled=true;status('#transcript','Listening…');}catch{status('#transcript','Voice could not start. Check microphone permission.');}};
function snapshot(kind,extra={}){const patient=extra.patient||null;const event={id:uid(),kind,lead:{...lead,clinicHours:{open:$('#openTime').value||'09:00',close:$('#closeTime').value||'17:00',step:Number($('#slotStep').value||30)},...(patient?{patientName:patient.name,patientPhone:patient.phone,customerEmail:patient.email}: {})},afterHours,lines:lines.map(l=>({...l})),bookings:bookings.map(b=>({...b,choices:[...b.choices]})),callbacks:callbacks.map(c=>({...c})),emailHistory:mailEvents.map(m=>`${titles[m.data.kind]}: ${Object.values(m.statuses).join(', ')}`).join('\n'),...extra};delete event.patient;return event;}
function renderEmails(){const root=$('#emailEvents');root.replaceChildren();if(!mailEvents.length)root.append(text('p','No emails generated yet. End a chat or submit a demo action.'));for(const event of [...mailEvents].reverse()){const card=text('article','','entry');card.append(text('h3',titles[event.data.kind]));for(const mail of event.mails){const detail=document.createElement('details');detail.append(text('summary',`${mail.role}: ${mail.to||'Provider address not configured'} — ${event.statuses[mail.role]}`),text('h4',mail.subject),text('pre',mail.body));card.append(detail);}if(!event.busy&&Object.values(event.statuses).some(s=>s!=='accepted')){const retry=text('button','Retry unconfirmed recipients','action secondary');retry.onclick=()=>deliver(event);card.append(retry,text('small','An uncertain timeout can still have sent a message. Check your inbox before retrying.'));}root.append(card);}}
async function deliver(event){if(event.busy)return false;event.busy=true;for(const mail of event.mails)if(event.statuses[mail.role]!=='accepted')event.statuses[mail.role]='sending';renderEmails();let ok=false;try{const response=await fetch('/api/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...event.data,website:$('#website').value,acceptedRoles:Object.keys(event.statuses).filter(k=>event.statuses[k]==='accepted')}),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Email request failed.');for(const s of result.statuses)event.statuses[s.role]=s.status;ok=result.ok;activity(titles[event.data.kind],ok?'All configured role messages accepted by sender':'Some messages need attention');}catch(error){for(const role of Object.keys(event.statuses))if(event.statuses[role]==='sending')event.statuses[role]='unconfirmed';activity('Email needs attention',error.message);event.error=error.message;}finally{event.busy=false;renderEmails();renderOwner();}if(ok&&event.onAccepted){event.onAccepted();event.onAccepted=null;}return ok;}
async function queue(kind,extra={},onAccepted=null){const data=snapshot(kind,extra);const mails=buildEmails(data,observer);const event={data,mails,statuses:Object.fromEntries(mails.map(m=>[m.role,'generated'])),busy:false,onAccepted};mailEvents.push(event);renderEmails();await deliver(event);return event;}
async function endChat(channel){if(!allowed()||channelBusy[channel])return;channelBusy[channel]=true;try{if(channel==='voice')await stopVoice();const end=lines.length;const selected=lines.slice(cursor[channel],end).filter(l=>l.channel===channel);if(!selected.some(l=>l.who==='Customer'))return toast('Add a customer question before ending the conversation.');cursor[channel]=end;const event=await queue(channel,{lines:selected});status(channel==='text'?'#textEmailStatus':'#voiceEmailStatus',Object.values(event.statuses).every(s=>s==='accepted')?'Three summary emails accepted by sender.':'Summary prepared. Check Email previews for individual statuses and retry.');}finally{channelBusy[channel]=false;}}
$('#endTextChat').onclick=()=>endChat('text');$('#voiceStop').onclick=()=>endChat('voice');
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:lead?.timezone||$('#timezone').value,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(v=>v.type===k).value).join('-');}
for(const id of ['date','dateB','dateC'])$('#'+id).min=today();
$('#bookingMode').onchange=()=>{const choices=$('#bookingMode').value==='choices';$('#extraChoices').hidden=!choices;$('#dateB').required=choices;$('#dateC').required=choices;};
function validSlot(slot){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(slot))return false;const [date,time]=slot.split('T'),d=new Date(date+'T12:00:00Z');if(isNaN(d)||d.toISOString().slice(0,10)!==date||date<today())return false;const start=$('#openTime').value||'09:00',end=$('#closeTime').value||'17:00',step=Number($('#slotStep').value||30),mins=Number(time.slice(0,2))*60+Number(time.slice(3)),startMins=Number(start.slice(0,2))*60+Number(start.slice(3));return mins>=startMins&&mins<Number(end.slice(0,2))*60+Number(end.slice(3))&&(mins-startMins)%step===0;}
$('#saveHours').onclick=()=>{const open=$('#openTime').value,close=$('#closeTime').value;if(!open||!close||open>=close)return status('#hoursStatus','Closing time must be later than opening time.');$('#hoursBadge').textContent=`${open}–${close}`;status('#hoursStatus',`Demo appointment requests now use ${open}–${close} at ${$('#slotStep').value}-minute intervals. No live calendar is connected.`);};
$('#bookingForm').addEventListener('submit',async e=>{e.preventDefault();if(!allowed())return;const mode=$('#bookingMode').value,patient=patientFields('booking');if(!patient.name||!patient.phone||!patient.email)return status('#bookingStatus','Enter the patient name, phone and email.');const choices=[`${$('#date').value}T${$('#time').value}`];if(mode==='choices')choices.push(`${$('#dateB').value}T${$('#timeB').value}`,`${$('#dateC').value}T${$('#timeC').value}`);if(choices.some(s=>!validSlot(s))||new Set(choices).size!==choices.length)return status('#bookingStatus','Choose distinct dates and times within the clinic’s configured hours. A, B and C are editable independently.');const service=$('#bookingService').value,claim=submissionLedger.claim(mode==='direct'?'direct-booking':'appointment-proposals',{service,choices,patient});if(!claim.allowed)return status('#bookingStatus',duplicateSubmissionMessage(claim.record.status,'identical appointment request'));const b={id:uid(),choices,selected:mode==='direct'?choices[0]:'',status:mode==='direct'?'Confirmed (demo only)':'Awaiting clinic confirmation',service,patient};bookings.push(b);renderOwner();e.submitter.disabled=true;try{const event=await queue(mode==='direct'?'booking':'choices',{service:b.service,choices,selected:b.selected,patient});const accepted=Object.values(event.statuses).every(s=>s==='accepted');submissionLedger.settle(claim.record,accepted?'accepted':'uncertain');status('#bookingStatus',accepted?(mode==='direct'?'Direct demo booking recorded; clinic and patient confirmation emails are shown in Email previews. No live calendar was checked.':'Three choices sent to the clinic. The clinic confirms one in Owner view; then both emails are sent.'):'The email or booking result is uncertain. Check Email previews and the provider before submitting the same request again.');}catch(error){submissionLedger.settle(claim.record,'uncertain');status('#bookingStatus','The request result is uncertain. Verify it with the provider before submitting the same request again.');}finally{e.submitter.disabled=false;}});
$('#callbackForm').addEventListener('submit',async e=>{e.preventDefault();if(!allowed())return;const patient=patientFields('callback'),request={service:$('#callbackService').value,urgency:$('#callbackUrgency').value,phone:patient.phone,reason:$('#callbackReason').value.trim(),patient:{name:patient.name,email:patient.email,phone:patient.phone}},claim=submissionLedger.claim('aileen-callback',request);if(!claim.allowed)return status('#callbackStatus',duplicateSubmissionMessage(claim.record.status,'identical callback request'));const c={id:uid(),...request,status:'Needs clinic follow-up',patient};callbacks.push(c);renderOwner();e.submitter.disabled=true;let callStatus='Callback tool unavailable',callbackCallId=null;try{const response=await fetch('/api/callback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:patient.phone,reason:c.reason,lead,patient}),signal:AbortSignal.timeout(20000)});const result=await response.json();if(response.ok&&result.requested===true){callStatus='Aileen callback initiated';callbackCallId=result.callId||null;submissionLedger.settle(claim.record,'accepted');}else{callStatus=result.error||'Callback outcome needs provider verification';submissionLedger.settle(claim.record,response.status>=500?'uncertain':'rejected');}}catch{callStatus='Callback outcome uncertain; verify with the provider before retrying';submissionLedger.settle(claim.record,'uncertain');}try{const event=await queue('callback',{...c,patient,callbackOutcome:callStatus,callbackCallId});if(!Object.values(event.statuses).every(s=>s==='accepted'))activity('Callback email needs attention','The callback attempt is recorded; verify the provider result before repeating it.');status('#callbackStatus',`${callStatus}. Clinic and patient email statuses appear in Email previews.`);}finally{e.submitter.disabled=false;}});
function button(label,action){const b=text('button',label,'action secondary');b.disabled=phase!=='active';b.onclick=async()=>{if(!allowed())return;b.disabled=true;try{await action();}finally{renderOwner();}};return b;}
function downloadCalendar(b){const escape=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const start=b.selected.replace(/[-:]/g,'')+'00';const d=new Date(b.selected+'Z');d.setUTCMinutes(d.getUTCMinutes()+30);const end=d.toISOString().slice(0,19).replace(/[-:]/g,'');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Aileen//Demo//EN','BEGIN:VEVENT',`UID:${b.id}@aileen-demo`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=${lead.timezone}:${start}`,`DTEND;TZID=${lead.timezone}:${end}`,`SUMMARY:${escape('DEMO ONLY — '+b.service)}`,'DESCRIPTION:Illustrative calendar entry. No actual appointment booked.','STATUS:TENTATIVE','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='aileen-demo-booking.ics';a.click();URL.revokeObjectURL(url);}
function renderOwner(){const summary=$('#ownerSummary');summary.replaceChildren(text('p',lead?`${lead.business} · ${lead.email} · ${afterHours?'After-hours routing':'Reception available'} · ${lead.timezone}`:'Start the demo to see session data.'));if(lead){const d=lead.discovery;const n=text('div','','entry');n.append(text('strong','Clinic discovery captured'),text('p',`Interested in: ${d.interest}`),text('p',`Priority: ${d.priority==='both'?'Revenue and patient experience':d.priority==='revenue'?'Revenue generation':'Patient experience'}`),text('p',`Clinic estimates: ${d.averageRevenue==null?'not supplied':new Intl.NumberFormat(undefined,{style:'currency',currency:d.currency}).format(d.averageRevenue)} average revenue per patient; ${d.missedAfterHours==null?'not supplied':d.missedAfterHours} missed after-hours patients/week.`));summary.append(n);}const er=$('#ownerEnquiries');er.replaceChildren();for(const q of enquiries){const n=text('div','','entry');n.append(text('strong',q.intent+' · '+q.urgency),text('p',q.question),text('p',`${q.route}: ${q.next}`));er.append(n);}for(const c of callbacks){const n=text('div','','entry');n.append(text('strong',`${c.service} · ${c.urgency}`),text('p',`${c.reason} · ${c.phone} · ${c.status}`),button('Mark reviewed (demo)',()=>{c.status='Reviewed in demo';}));er.append(n);}if(!enquiries.length&&!callbacks.length)er.append(text('p','No enquiries yet.'));
 const br=$('#ownerBookings');br.replaceChildren();if(!bookings.length)br.append(text('p','No bookings yet.'));for(const b of bookings){const n=text('article','','entry');n.append(text('h3',b.service),text('p',b.status),text('p',b.selected?`${b.selected.replace('T',' ')} · ${lead.timezone}`:'Select one proposed time:'));if(!b.selected&&b.status!=='Cancelled (demo)')b.choices.forEach((slot,i)=>n.append(button(`Clinic confirms ${'ABC'[i]}: ${slot.replace('T',' ')}`,async()=>{const claim=submissionLedger.claim('clinic-appointment-confirmation',{bookingId:b.id});if(!claim.allowed)return toast(duplicateSubmissionMessage(claim.record.status,'clinic appointment confirmation'));b.selected=slot;b.status='Confirming in demo…';renderOwner();try{const event=await queue('booking',{service:b.service,selected:slot,patient:b.patient});const accepted=Object.values(event.statuses).every(s=>s==='accepted');submissionLedger.settle(claim.record,accepted?'accepted':'uncertain');b.status=accepted?'Clinic-confirmed in demo':'Confirmation outcome uncertain — verify before retrying';}catch{submissionLedger.settle(claim.record,'uncertain');b.status='Confirmation outcome uncertain — verify before retrying';}})));
 if(b.selected&&b.status!=='Cancelled (demo)'){n.append(button('Download demo calendar entry',()=>downloadCalendar(b)),button('Send example reminder',()=>queue('reminder',{service:b.service,selected:b.selected,patient:b.patient})),button('Cancel demo booking',async()=>{b.status='Cancelled (demo)';await queue('cancel',{service:b.service,selected:b.selected,patient:b.patient});}));const label=text('label','New date and time');const date=document.createElement('input');date.type='date';date.min=today();date.value=b.selected.slice(0,10);const time=document.createElement('input');time.type='time';time.step='900';time.value=b.selected.slice(11);label.append(date,time);n.append(label,button('Reschedule demo booking',async()=>{const slot=date.value+'T'+time.value;if(!validSlot(slot))return toast('Choose a future time within the configured clinic hours.');b.selected=slot;b.status='Rescheduled (demo)';await queue('reschedule',{service:b.service,selected:slot,patient:b.patient});}));}br.append(n);}}
const packages=[['Conversion System','Captures interest without a conversational agent.','Demonstrated: lead form and email contact capture.','Production scope: conversion-focused pages, click-to-call, WhatsApp, trust signals and tracking.'],['Booking Engine','Converts an enquiry into an agreed time.','Demonstrated: direct demo booking, A/B/C owner selection, confirmations, calendar download, reschedule and cancel.','Illustrative: reminders and calendar entries. Production integration: real availability, calendar sync and scheduled reminders.'],['AI Revenue System','Answers and qualifies enquiries at any hour.','Demonstrated: scripted text, browser voice, urgency flags, after-hours routing and summaries.','Production integration: AI knowledge, live service routing, CRM/lead board and source reporting.'],['Advanced AI Revenue','Adds telephone reception and ongoing follow-up.','Illustrated: callback capture and owner follow-up review.','Requires deployment: inbound/outbound calls, missed-call text-back, multi-location escalation, quote follow-up, reactivation, reviews and revenue reporting.']];
for(const p of packages){const card=text('article','','entry');card.append(text('h3',p[0]));for(const copy of p.slice(1))card.append(text('p',copy));$('#packageCards').append(card);}
$('#calculateRoi').onclick=()=>{if(!lead?.discovery)return status('#roiResult','Start the discovery intake first.');const d=lead.discovery;if(!Number.isFinite(d.averageRevenue)||!Number.isFinite(d.missedAfterHours))return status('#roiResult','Enter the clinic’s own average revenue and missed-patient estimates to show an optional illustration.');const assumedRecovery=10;const annual=d.missedAfterHours*d.averageRevenue*52;const scenarioValue=annual*assumedRecovery/100;const fmt=new Intl.NumberFormat(undefined,{style:'currency',currency:d.currency,maximumFractionDigits:0});status('#roiResult',`Illustration only: ${d.missedAfterHours} missed patients/week × ${fmt.format(d.averageRevenue)} × 52 = ${fmt.format(annual)} estimated annual gross value if every patient attended. At an editable-in-discussion 10% assumed recovery, the scenario is ${fmt.format(scenarioValue)}/year. This is not a forecast, profit estimate, or guarantee.`);};
$('#feedbackForm').addEventListener('submit',async e=>{e.preventDefault();if(!allowed())return;const feedback=[...document.querySelectorAll('input[name="toolValue"]:checked')].map(x=>x.value);if(!feedback.length)return status('#feedbackStatus','Select at least one tool.');phase='finishing';$('#finishDemo').disabled=true;await stopVoice();const event=await queue('demo',{feedback});phase='finished';$('#finishDemo').textContent='Demo complete';status('#feedbackStatus','Feedback saved. Final clinic summary status is shown in Email previews.');status('#gateStatus','Demo complete. Review the clinic summary and email statuses.');status('#summaryStatus',Object.values(event.statuses).every(s=>s==='accepted')?'Final clinic and patient summaries accepted by sender.':'Final summary is prepared; review individual email statuses.');renderOwner();});
renderOwner();renderEmails();
fetch('/api/health').then(r=>r.json()).then(h=>{observer=h.observerEmail||'';configured=h.emailConfigured;status('#summaryStatus',`${configured?'Clinic/patient email sender connected':'Email sender not connected; previews remain available'} · ${h.callbackConfigured?'Aileen callback tool connected':'Aileen callback tool not connected'}.`);if(h.version!==VERSION)status('#summaryStatus','Page and server versions differ. Refresh after deployment completes.');}).catch(()=>status('#summaryStatus','Demo service status unavailable. Email previews remain available.'));
